# Generated by Django 5.1.7 on 2025-03-21 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MulberryFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('size', models.FloatField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sericulture.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='SilkwormBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('start_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sericulture.mulberryfarm')),
            ],
        ),
    ]
